# Generated by Django 5.0.6 on 2024-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('patientid', models.CharField(max_length=50, null=True)),
                ('passcode', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('age', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'patientRegistration',
            },
        ),
        migrations.CreateModel(
            name='PatientUploadData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctoremail', models.CharField(max_length=50, null=True)),
                ('patientid', models.CharField(max_length=50)),
                ('patientemail', models.EmailField(max_length=254)),
                ('patientname', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(null=True, upload_to='encrypted_patientfiles/%y')),
                ('normalfiles', models.FileField(null=True, upload_to='normalfiles/%y')),
                ('encryption_key', models.BinaryField()),
                ('status', models.CharField(default='pending', max_length=50, null=True)),
                ('key', models.BinaryField(max_length=255, null=True)),
                ('salt', models.CharField(max_length=255, null=True)),
                ('iv', models.BinaryField(max_length=255, null=True)),
                ('tag', models.BinaryField(max_length=255, null=True)),
                ('random_password', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'PatientUploadData',
            },
        ),
    ]
