# Generated by Django 3.2.25 on 2025-12-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientregistration',
            name='addar_card',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientuploaddata',
            name='key',
            field=models.BinaryField(null=True),
        ),
    ]
