# Generated by Django 3.2.25 on 2025-12-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PatientApp', '0002_auto_20251208_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useremail', models.EmailField(max_length=254, null=True)),
                ('card_number', models.CharField(max_length=50, null=True)),
                ('amount', models.CharField(max_length=10, null=True)),
                ('expery_date', models.CharField(max_length=50, null=True)),
                ('cvv', models.CharField(max_length=10, null=True)),
                ('doctoremail', models.EmailField(max_length=254, null=True)),
            ],
            options={
                'db_table': 'payment_model',
            },
        ),
        migrations.RemoveField(
            model_name='patientuploaddata',
            name='iv',
        ),
        migrations.RemoveField(
            model_name='patientuploaddata',
            name='salt',
        ),
        migrations.RemoveField(
            model_name='patientuploaddata',
            name='tag',
        ),
    ]
