# Generated by Django 5.0.6 on 2024-06-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('doctorid', models.CharField(max_length=50, null=True)),
                ('hospital', models.CharField(max_length=50, null=True)),
                ('proffesion', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('passcode', models.CharField(max_length=10)),
                ('contact', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'db_table': 'DoctorRegistration',
            },
        ),
    ]
